# Generated by Django 5.0.6 on 2024-06-20 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_latin', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_found', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='finding_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.profile')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='viewer.finding')),
            ],
        ),
        migrations.CreateModel(
            name='Mushroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cz', models.CharField(max_length=100)),
                ('name_latin', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('edibility', models.CharField(choices=[('jedla', 'Jedlá'), ('nejedla', 'Nejedlá'), ('jedovata', 'Jedovatá')], default='inedible', max_length=10)),
                ('habitat', models.CharField(choices=[('listnaty', 'Listnatý les'), ('jehlicnaty', 'Jehličnatý les'), ('smiseny', 'Smíšený les'), ('louka', 'Louka'), ('jine', 'Jiné')], default='mixed', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mushroom_images/')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mushrooms', to='viewer.family')),
            ],
        ),
        migrations.AddField(
            model_name='finding',
            name='mushroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='viewer.mushroom'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('main_mushroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='viewer.mushroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='accounts.profile')),
            ],
        ),
    ]
