# Generated by Django 5.0.6 on 2024-06-22 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_username_profile_user_remove_profile_email_and_more'),
        ('viewer', '0002_tip_alter_recipe_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
        migrations.AddField(
            model_name='tip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tip', to='accounts.profile'),
        ),
    ]
