# Generated by Django 5.0.6 on 2024-06-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_habitat_alter_family_options_alter_mushroom_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='location',
        ),
        migrations.AddField(
            model_name='finding',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finding',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
