# Generated by Django 5.0.6 on 2024-07-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_alter_recipe_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name'], 'verbose_name_plural': 'Families'},
        ),
    ]
