# Generated by Django 5.0.6 on 2024-07-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_alter_comment_options_comment_new'),
        ('viewer', '0010_alter_comment_options_recipe_rating'),
    ]

    operations = [
    ]
