# Generated by Django 5.0.6 on 2024-07-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_alter_recipe_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrecipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments_images/'),
        ),
    ]
