# Generated by Django 5.0.6 on 2024-07-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
