# Generated by Django 5.0.6 on 2024-07-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_message_is_deleted_by_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_trashed_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_trashed_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
